<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.samancore</groupId>
        <artifactId>operation</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>operation-data</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <commons-lang3.version>3.14.0</commons-lang3.version>
        <operation-model.version>1.0.0-SNAPSHOT</operation-model.version>
        <common.version>1.0.0-SNAPSHOT</common.version>
        <common-error.version>1.0.0-SNAPSHOT</common-error.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.samancore</groupId>
            <artifactId>operation-model</artifactId>
            <version>${operation-model.version}</version>
        </dependency>
        <dependency>
            <groupId>io.samancore</groupId>
            <artifactId>common</artifactId>
            <version>${common.version}</version>
        </dependency>
        <dependency>
            <groupId>io.samancore</groupId>
            <artifactId>common-error</artifactId>
            <version>${common-error.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
